### ISSUE TITLE
Upload all project files

### ISSUE THREAD

**Issue by ashyAU** [Rubita048/Hypixel-Skyblock-Fishing-Timer#1]
Hello, I can't work on the repo unless you upload all the files contained within.

Please update this so I can improve it.

Appreciate it!

**Comment by Rubita048** [comment]
Hello, firstly i was did it for getting fishing 50 at first place. I was a
junior dev at those times and posting all programs i made basicly :)

Secondly. Like 2 months after i released that, hypixel added very same
thing to skyblock (that timer when u throw fishing rod in settings) so it
doesnt needs to be updated anymore.

Thank you so much for offer.
